alfitra_cpt_evenement:
    resource: "@AlfitraCptBundle/Controller/EvenementController.php"
    type:     annotation

alfitra_cpt_collecteur:
    resource: "@AlfitraCptBundle/Controller/CollecteurController.php"
    type:     annotation

alfitra_cpt_formulaire:
    resource: "@AlfitraCptBundle/Controller/FormulaireController.php"
    type:     annotation

alfitra_cpt_ecran:
    resource: "@AlfitraCptBundle/Controller/EcranController.php"
    type:     annotation

alfitra_dashboard:
    path:     /
    defaults: { _controller: AlfitraCptBundle:Dashboard:index }

compteur:
    path:     /compteur
    defaults: { _controller: AlfitraCptBundle:Compteur:index }

compteur_nb:
    path:     /compteur-nb
    defaults: { _controller: AlfitraCptBundle:Compteur:getNb }

challenge:
    path:     /challenge
    defaults: { _controller: AlfitraCptBundle:Challenge:index }

donateurs:
    path:     /donateurs
    defaults: { _controller: AlfitraCptBundle:Donateur:index }

increment:
    path:     /increment/{id_evnmt}
    defaults: { _controller: AlfitraCptBundle:Donateur:increment }

remove_don:
    path:     /remove/don/{id_don}
    defaults: { _controller: AlfitraCptBundle:Donateur:remove }

chart:
    path:     /chart
    defaults: { _controller: AlfitraCptBundle:Challenge:sellsHistory }

# reset:
#     path:     /Bourget2016reset
#     defaults: { _controller: AlfitraCptBundle:Dashboard:reset }


