<?php

namespace Alfitra\CptBundle\Repository;

/**
 * CollecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollecteurRepository extends \Doctrine\ORM\EntityRepository
{

	public function getNb(){
		$query = $this->createQueryBuilder('c');
		return $query->select('count(c)')
			  ->getQuery()->getSingleScalarResult();
	}
}
