<?php

namespace Alfitra\CptBundle\Repository;

/**
 * FormulaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulaireRepository extends \Doctrine\ORM\EntityRepository
{

	public function getTotalMontant(){
		$query = $this->createQueryBuilder('f');
		return $query->select('sum(f.montant)')
					->andWhere("f.modePaiement != 'Mensuel'")
					->andWhere("f.announced = 1")
		  ->getQuery()->getSingleScalarResult();
	}

	public function getTotalMensuel(){
		$query = $this->createQueryBuilder('f');
		return $query->select('sum(f.montant)')
					->andWhere("f.modePaiement = 'Mensuel'")
					->andWhere("f.announced = 1")
		  ->getQuery()->getSingleScalarResult();
	}

	public function getTotalCash(){
		$query = $this->createQueryBuilder('f');
		return $query->select('sum(f.montant)')
					->orWhere("f.modePaiement = 'CB'")
					->orWhere("f.modePaiement = 'Cheque'")
					->orWhere("f.modePaiement = 'Espece'")
					->andWhere("f.announced = 1")
		  ->getQuery()->getSingleScalarResult();
	}

	public function getTotalPromesse(){
		$query = $this->createQueryBuilder('f');
		return $query->select('sum(f.montant)')
					->andWhere("f.modePaiement = 'Promesse'")
					->andWhere("f.announced = 1")
		  ->getQuery()->getSingleScalarResult();
	}

}
